### ISSUE TITLE
[Epic] Implement Dog breeds page

### ISSUE THREAD

**Issue by ashalva** [ashalva/ios.memenator#2]
# Dog Breeds

We need to implement totally new page about dog facts.

The API: https://dogapi.dog/api/v2

- [x] Add new list item in main page
- [x] Once user clicks on the item redirect to `DogBreedsListView` page
- [x] `DogBreedsListView` page should have list with dog breeds: https://dogapi.dog/api/v2/breeds
- [x]  Whenever user taps on any breed we need to open `DogBreedDetailView`: https://dogapi.dog/api/v2/breeds/68f47c5a-5115-47cd-9849-e45d3c378f12

### UI

- [x] Create new files `DogBreedsListView` and `DogBreedsListViewModel`
- [x] Add new list item in main page which will open empty `DogBreedsListView`
- [x] Each list item should contain:

1. Name
3. Min life age
4. Max life age

`DogBreedsListView` has the list of dog `breeds` which must be fetched from `https://dogapi.dog/api/v2/breeds`. See section **API** for more details. Once user taps on any breed we need to open the detail page, so:

- [x] Create the `DogBreedDetailView` and `DogBreedDetailViewModel`
- [x] We need to display dog details here 👇 

1. Name
2. Description
3. Min life age
4. Max life age
5. Male weight
6. Female weight

#### DTOs

- [x] Create `DogBreedsResultDTO` under Services/DTOs

<details>

```swift
import Foundation

// MARK: - DogBreedsResultDTO
struct DogBreedsResultDTO: Codable {
    let data: [DogBreedsDataDTO]
}

// MARK: - DogBreedsDataDTO
struct DogBreedsDataDTO: Codable {
    let id: String
    let attributes: Attributes

    struct Attributes: Codable {
        struct Weight: Codable {
            let max, min: Int
        }

        struct Life: Codable {
            let max, min: Int
        }

        let name: String
        let description: String
        let life: Life
        let maleWeight: Weight
        let femaleWeight: Weight

        enum CodingKeys: String, CodingKey {
            case name
            case description
            case life
            case maleWeight = "male_weight"
            case femaleWeight = "female_weight"
        }
    }
}
```

</details>

#### Business Models

- [x] Create `DogBreed` under Services/BusinessModels.

<details>

```swift
struct DogBreed {
    let name: String
    let description: String
    let minLife: Int
    let maxLife: Int
    let maleMinWeight: Int
    let maleMaxWeight: Int
    let femaleMinWeight: Int
    let femaleMaxWeight: Int
}
```

</details>

### API

- [x] Create `DogBreedsService` in Network/Services folder
- [x] Create `DogBreedsMapper` under `Network/Mappers`
- [x] Create endpoint getDogBreeds() -> Future<[DogBreed], Error> it should return the array of dog breeds. The url: https://dogapi.dog/api/v2/breeds
- [x] Create endpoint getDogBreedDetail(id: String) -> Future<DogBreed, Error>. The url: https://dogapi.dog/api/v2/breeds/68f47c5a-5115-47cd-9849-e45d3c378f12

**Comment by ashalva** [comment]
1st Sprint

1st PR
1. Create new files DogBreedsListView and DogBreedsListViewModel
2. Add new list item in main page which will open empty DogBreedsListView

2nd PR
1. Create `DogBreed` Model with name, min age and max age properties.
2. Create array of dog breeds in viewmodel
4. Show dog breeds in view.

**Comment by ashalva** [comment]
## Sprint 2

Sprint goal 🎯 

We need to show real dog breeds which are fetched from the server. Whenever user opens the dogs list we need to show loading view and after that show dog breeds. If request fails, we need to show error view.


### Pull Request 1 - Create service

You can always check `RedditService` for references.

1. Create `DogBreedsListDTO` under `Network/DTOs` 👇 

<details>

```swift
struct DogBreedDTO: Codable {
    struct Attributes: Codable {
        struct Weight: Codable {
            let max, min: Double
        }

        struct Life: Codable {
            let max, min: Double
        }


        let name, description: String
        let life: Life
        let maleWeight, femaleWeight: Weight
        let hypoallergenic: Bool

        enum CodingKeys: String, CodingKey {
            case name, description, life
            case maleWeight = "male_weight"
            case femaleWeight = "female_weight"
            case hypoallergenic
        }
    }

    let id: String
    let type: String
    let attributes: Attributes
}

struct DogBreedsListDTO: Codable {
    let data: [DogBreedDTO]
}
```

</details>

2. Create `DogBreedService` file, we will need one protocol `DogBreedServing` and class `DogBreedService`. It can be in the same file.
3. Add function in `DogBreedServing`, `func getDogBreeds() -> AnyPublisher<[DogBreed], Error>`
4. Define `dogBreedApiURL` constant which will have a value `https://dogapi.dog/api/v2/`
5. Implement mapper `DogBreedMapper` which will map `DogBreedDTO` to `DogBreed`, check how `RedditPostMapper` is written
5. Implement `getDogBreeds` in `DogBreedService` 👇 
```swift
func getDogBreeds() -> AnyPublisher<[DogBreed], Error> {
    let request = Endpoint<DogBreedsListDTO>(baseURL: dogBreedApiURL)
        .appendingPathParameter("breeds")
        .usingDefaultParameters()
    
    return try! request
        .usingMethod(.GET)
        .build()
        .asFuture()
        .map {
               $0.data.map { breed in DogBreedMapper.toEntity(dto: breed) }
        }
        .eraseToAnyPublisher()
}
```

### Pull Request 2 - Show real dog breeds

1. Add service property in viewmodel
2. Remove fake data from array of `DogBreed`
3. Create function `getDogBreeds()` in viewmodel  and call `DogBreedService`'s new function you have implemented above.
4. Check how `RedditViewModel` calls service function. You will need to change  `receiveCompletion` and `receiveValue` callbacks.

### Pull Request 3 - Show loading and error states

1. Add new @Published properties in viewmodel: `isLoading`, `hasError`
2. Whenever `getDogBreeds()` is called we need to set `isLoading` to true
3. Whenever we receive the response (`receiveCompletion` or `receiveValue` is called) we need to set it back to false
4. Whenever error happens we need to set `hasError` to true, otherwise false.

**Comment by ashalva** [comment]
# Sprint 3

### Pull Request 1 - Open empty view

1. Add empty `DogBreedDetailView` and `DogBreedDetailViewModel`
2. When user taps on any dog breed in the list view, we should navigate to the new, empty `DogBreedDetailView`

### Pull Request 2 - Update struct

1. Remove manual assignment of `id` in `DogBreed`
2. Update `DogBreedsMapper` and pass id to `DogBreed` from `DogBreedDTO`

### Pull Request 3 - Add service function for details

1. Add new struct `DogBreedDetailDTO` with single property `let data: DogBreedDTO`
2.  Add new function in `DogBreedServing`
```swift
func getDogBreedDetails(with id: String) -> AnyPublisher<DogBreed, Error>
```
3. Add implementation of `getDogBreedDetails` in `DogBreedsService`
    1. Endpoint should look like this `Endpoint<DogBreedDetailDTO>`
    2. Path parameter should be `"breeds/\(id)"`
    3. You need to map like this: `DogBreedsMapper.toEntity(dto: $0.data)`

### Pull Request 4 - Show details 

1. Add service instance variable in viewmodel
2. Add function in viewmodel to fetch dog breed details, where you will call service function
3. When dog breed details is fetched show all properties on the screen

### Pull Request 5 - Loader & Error

1. Add spinner for loading - when request is ongoing
2. Add error text - when request failed
